services:
  satisfactory:
    image: wolveix/satisfactory-server:latest
    container_name: satisfactory
    hostname: satisfactory

    restart: unless-stopped

    ports:
      - "7777:7777/tcp"
      - "7777:7777/udp"
      - "8888:8888/tcp"

    environment:
      MAXPLAYERS: "4"
      STEAMBETA: "false"
      PUID: "1000"
      PGID: "1000"

    volumes:
      - /srv/docker/data/games/satisfactory:/config

    deploy:
      resources:
        limits:
          memory: 8G
        reservations:
          memory: 4G
